# Generated by Django 2.1.5 on 2019-02-13 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organiztion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='الموضوع')),
                ('in_number', models.IntegerField(blank=True, null=True, verbose_name='رقم وارد')),
                ('in_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ وارد')),
                ('out_number', models.IntegerField(blank=True, null=True, verbose_name='رقم صادر')),
                ('out_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ صادر')),
                ('post_flag', models.CharField(blank=True, choices=[('I', 'وارد'), ('O', 'صادر')], default='I', max_length=1, null=True, verbose_name='نوع المخاطبة')),
                ('files', models.FileField(blank=True, null=True, upload_to='', verbose_name='ملف')),
                ('organization', models.ManyToManyField(to='auth.Group', verbose_name='توجيه')),
                ('otherpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='ربط')),
            ],
        ),
    ]
