# Generated by Django 2.1.5 on 2019-02-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='organization',
            field=models.ManyToManyField(to='users.Department', verbose_name='توجيه'),
        ),
    ]
