# Generated by Django 2.1.5 on 2019-02-16 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190216_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='organization',
            new_name='department',
        ),
    ]
