# Generated by Django 2.1.5 on 2019-02-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190216_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='department',
            new_name='departments',
        ),
    ]
