# Generated by Django 2.1.5 on 2019-02-13 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
    ]
